# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:
  walletstore:
  grafana-storage:
  prometheus-storage:

services:

  explorerdb:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb
    hostname: explorerdb
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=adminpw
    volumes:
      - ./explorer_artifacts/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
    networks:
      - simplehlfnet

  explorer:
    image: hyperledger/explorer:latest
    container_name: explorer
    hostname: explorer
    environment:
      - DATABASE_HOST=explorerdb
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWD=adminpw
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./explorer_artifacts/config.json:/opt/explorer/app/platform/fabric/config.json
      - ./explorer_artifacts/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./msp:/tmp/crypto
      - walletstore:/opt/wallet
    command: /bin/sh -c "sleep 16&& node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 8090:8080
    networks:
      - simplehlfnet

  proms:
    container_name: proms
    image: prom/prometheus:latest
    volumes:
      - ./explorer_artifacts/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - simplehlfnet

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./explorer_artifacts/balance-transfer-grafana-dashboard.json:/var/lib/grafana/dashboards/mydashboard.json
      - ./explorer_artifacts/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    ports:
      - '3000:3000'
    networks:
      - simplehlfnet

networks:
  simplehlfnet:
    external: true